In [106]:
import os
import numpy as np

from astropy.table import Table
import astropy.units as units
from astropy.coordinates import Angle

from pyradiosky import SkyModel

In [17]:
filename = "/Users/bryna/Downloads/LoBES_EoR0_FULL_FINAL_SpecGaussModCat_17Sep2021.fits"

In [18]:
table = Table.read(filename)

In [25]:
ext_model_name = np.asarray([name[:14] for name in table["NAME"]])

In [26]:
print(ext_model_name.size)
print((np.unique(ext_model_name)).size)

88613
80861


In [29]:
src_id = np.asarray(table["UNQ_SOURCE_ID"].data).astype(int)
print(src_id.size)
print((np.unique(src_id)).size)

88613
80862


In [45]:
counts = np.bincount(src_id)
multiple_src_inds = (np.arange(counts.size))[np.nonzero(counts > 1)]
multiple_src_inds

array([   15,    28,    45, ..., 80859, 80860, 80861])

In [53]:
for ind in np.arange(counts.size):
    this_source_names = ext_model_name[np.nonzero(src_id == ind)]
    other_source_names = ext_model_name[np.nonzero(src_id != ind)]
    assert np.all(this_source_names == this_source_names[0])
    assert not np.any(other_source_names == this_source_names[0]), f"src ind: {ind}"

AssertionError: 

In [54]:
print(ind)

66309


In [55]:
ext_model_name[np.nonzero(src_id == ind)]

array(['SNG010918-4453'], dtype='<U14')

In [57]:
np.nonzero(src_id == ind)[0]

array([72603])

In [58]:
np.nonzero(ext_model_name == 'SNG010918-4453')[0]

array([72603, 88301])

In [59]:
table["NAME"][[72603, 88301]]

<Column name='NAME' dtype='bytes36' length=2>
SNG010918-4453_GIDU72629
SNG010918-4453_GIDU88344

In [60]:
table["UNQ_SOURCE_ID"][[72603, 88301]]

<Column name='UNQ_SOURCE_ID' dtype='bytes11' length=2>
66309
80790

In [107]:
Angle(table["RA"][[72603, 88301]]).hms

hms_tuple(h=array([1., 1.]), m=array([9., 9.]), s=array([18.94748703, 18.04757254]))

In [108]:
Angle(table["DEC"][[72603, 88301]]).dms

dms_tuple(d=array([-44., -44.]), m=array([-53., -53.]), s=array([ -5.86940479, -33.44815374]))

In [63]:
print(counts[66309])
print(counts[80790])

1
1


In [99]:
ext_model_name_use = np.full((table["NAME"].size), "", dtype="<U14")
for ind in multiple_src_inds:
    this_orig_inds = np.nonzero(src_id == ind)[0]
    this_names_arr = np.asarray([name[:14] for name in (table["NAME"])[this_orig_inds]])
    this_name = this_names_arr[0]
    assert np.all(this_names_arr == this_name)
    if this_name in ext_model_name_use:
        this_name += "_" + str(ind)
        print("name exists, adding ind")
    ext_model_name_use[this_orig_inds] = this_name


In [101]:
ext_model_name_use[np.nonzero(src_id == multiple_src_inds[0])]

array(['MLT011814-4027', 'MLT011814-4027'], dtype='<U14')

In [100]:
ext_model_name_use

array(['', '', '', ..., 'COM001751-2221', 'COM001751-2221',
       'COM001751-2221'], dtype='<U14')