In [1]:
import numpy as np
import copy

In [2]:
delta_t = 0.5
times = np.arange(0, 20, delta_t, dtype=np.float64)
nt = np.size(times)
period = np.max(times) - np.min(times) + delta_t 
omega = 2 * np.pi * np.arange(0, nt) / period

In [3]:
times

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [4]:
omega

array([ 0.        ,  0.31415927,  0.62831853,  0.9424778 ,  1.25663706,
        1.57079633,  1.88495559,  2.19911486,  2.51327412,  2.82743339,
        3.14159265,  3.45575192,  3.76991118,  4.08407045,  4.39822972,
        4.71238898,  5.02654825,  5.34070751,  5.65486678,  5.96902604,
        6.28318531,  6.59734457,  6.91150384,  7.2256631 ,  7.53982237,
        7.85398163,  8.1681409 ,  8.48230016,  8.79645943,  9.1106187 ,
        9.42477796,  9.73893723, 10.05309649, 10.36725576, 10.68141502,
       10.99557429, 11.30973355, 11.62389282, 11.93805208, 12.25221135])

In [5]:
omega_t_arr = np.outer(times, omega) # first axis is time
cos_arr = np.cos(omega_t_arr)
sin_arr = np.sin(omega_t_arr)

In [6]:
variances_const = np.ones((nt, 1))*5
variance_const_arr = np.repeat(variances_const, nt, axis=1)

In [7]:
numerator_const = 2 * np.sum(variance_const_arr * cos_arr * sin_arr, axis=0)
numerator_const

array([ 0.00000000e+00,  8.88178420e-16,  4.44089210e-16,  0.00000000e+00,
        3.55271368e-15,  2.66453526e-14, -5.15143483e-14,  1.50990331e-14,
        7.10542736e-15,  6.01740879e-14, -5.51710040e-15, -2.44249065e-15,
        5.37347944e-14, -1.10134124e-13,  5.15143483e-14,  5.50670620e-14,
        1.86517468e-14, -1.16351373e-13, -2.65121258e-13,  4.35207426e-14,
       -1.06180591e-12,  1.84297022e-14, -3.55271368e-15,  1.74082970e-13,
       -5.32907052e-14, -9.32587341e-14,  1.69642078e-13,  3.28626015e-13,
        2.40696352e-13,  1.89848137e-13, -1.76423417e-13,  8.65973959e-14,
        3.99680289e-14, -2.53130850e-13, -8.43769499e-14,  9.14823772e-14,
        2.36255460e-13,  3.71258579e-13, -2.48245868e-13,  1.49213975e-13])

In [8]:
np.isclose(numerator_const, 0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [9]:
denominator_const = np.sum(variance_const_arr * cos_arr**2, axis=0) - np.sum(variance_const_arr * sin_arr**2, axis=0)
denominator_const

array([ 2.00000000e+02,  0.00000000e+00,  1.42108547e-14,  2.84217094e-14,
        5.68434189e-14, -1.70530257e-13,  1.42108547e-14,  8.52651283e-14,
       -1.42108547e-14, -1.42108547e-14,  0.00000000e+00,  1.42108547e-14,
        1.56319402e-13,  1.13686838e-13,  8.52651283e-14,  9.94759830e-14,
       -4.26325641e-14, -5.68434189e-14,  1.13686838e-13,  8.52651283e-14,
        2.00000000e+02, -7.10542736e-14, -5.25801624e-13,  5.68434189e-14,
        0.00000000e+00,  5.68434189e-14,  4.83169060e-13, -1.56319402e-13,
        2.41584530e-13, -7.10542736e-14,  0.00000000e+00,  1.56319402e-13,
       -1.42108547e-14,  0.00000000e+00,  9.94759830e-14, -2.13162821e-13,
        3.41060513e-13,  2.84217094e-13,  3.12638804e-13, -1.42108547e-14])

In [10]:
np.isclose(denominator_const, 0)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [11]:
theta_const = np.arctan(numerator_const/denominator_const)/2.
theta_const

/Users/bryna/anaconda/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 0.00000000e+00,  7.85398163e-01,  1.56199167e-02,  0.00000000e+00,
        3.12094050e-02, -7.74983710e-02, -6.50814417e-01,  8.76331880e-02,
       -2.31823805e-01, -6.69441561e-01, -7.85398163e-01, -8.51059626e-02,
        1.65548038e-01, -3.84763240e-01,  2.71738797e-01,  2.52790527e-01,
       -2.06205221e-01,  5.58175456e-01, -5.82851199e-01,  2.35973087e-01,
       -2.65451478e-15, -1.26891272e-01,  3.37832697e-03,  6.27590332e-01,
       -7.85398163e-01, -5.11701719e-01,  1.68828528e-01, -5.63398422e-01,
        3.91778272e-01, -6.06333341e-01, -7.85398163e-01,  2.52945825e-01,
       -6.14590418e-01, -7.85398163e-01, -3.51728226e-01, -2.02697276e-01,
        3.02907723e-01,  4.58708560e-01, -3.35546296e-01, -7.37922310e-01])

In [12]:
theta_const_clipped = copy.copy(theta_const)
theta_const_clipped[np.where(np.isclose(numerator_const, 0))] = 0
theta_const_clipped

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [13]:
variances_vary = np.random.randn(nt)*5
variances_vary = variances_vary[:, np.newaxis]
variance_vary_arr = np.repeat(variances_vary, nt, axis=1)

In [14]:
numerator_vary = np.sum(variance_vary_arr * cos_arr * sin_arr, axis=0)
numerator_vary

array([ 0.00000000e+00,  5.13043263e+00,  7.31692614e+00,  2.17433356e+00,
        1.85370587e+00, -3.77053759e+00, -4.48688330e-01,  2.74274155e+01,
        1.21462036e-01,  4.05007421e+00,  1.23898361e-13, -4.05007421e+00,
       -1.21462036e-01, -2.74274155e+01,  4.48688330e-01,  3.77053759e+00,
       -1.85370587e+00, -2.17433356e+00, -7.31692614e+00, -5.13043263e+00,
        2.71455675e-13,  5.13043263e+00,  7.31692614e+00,  2.17433356e+00,
        1.85370587e+00, -3.77053759e+00, -4.48688330e-01,  2.74274155e+01,
        1.21462036e-01,  4.05007421e+00,  1.26485492e-13, -4.05007421e+00,
       -1.21462036e-01, -2.74274155e+01,  4.48688330e-01,  3.77053759e+00,
       -1.85370587e+00, -2.17433356e+00, -7.31692614e+00, -5.13043263e+00])

In [15]:
np.isclose(numerator_vary, np.zeros(nt))

array([ True, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False])

In [16]:
denominator_vary = np.sum(variance_vary_arr * cos_arr**2, axis=0) - np.sum(variance_vary_arr * sin_arr**2, axis=0)
denominator_vary

array([-42.61749661, -17.96494605, -18.05818532,  -9.72083371,
        17.46123701, -23.63911406,  16.3186698 ,   1.14176172,
       -16.98209354, -36.04690209, -39.92686599, -36.04690209,
       -16.98209354,   1.14176172,  16.3186698 , -23.63911406,
        17.46123701,  -9.72083371, -18.05818532, -17.96494605,
       -42.61749661, -17.96494605, -18.05818532,  -9.72083371,
        17.46123701, -23.63911406,  16.3186698 ,   1.14176172,
       -16.98209354, -36.04690209, -39.92686599, -36.04690209,
       -16.98209354,   1.14176172,  16.3186698 , -23.63911406,
        17.46123701,  -9.72083371, -18.05818532, -17.96494605])

In [17]:
np.isclose(denominator_vary, 0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [18]:
theta_vary = np.arctan2(numerator_vary, denominator_vary)/2.
theta_vary

array([ 1.57079633,  1.43170849,  1.37831174,  1.46076858,  0.05288253,
       -1.49171043, -0.01374424,  0.76459593,  1.56722021,  1.5148531 ,
        1.57079633, -1.5148531 , -1.56722021, -0.76459593,  0.01374424,
        1.49171043, -0.05288253, -1.46076858, -1.37831174, -1.43170849,
        1.57079633,  1.43170849,  1.37831174,  1.46076858,  0.05288253,
       -1.49171043, -0.01374424,  0.76459593,  1.56722021,  1.5148531 ,
        1.57079633, -1.5148531 , -1.56722021, -0.76459593,  0.01374424,
        1.49171043, -0.05288253, -1.46076858, -1.37831174, -1.43170849])

In [19]:
theta_vary_clipped = copy.copy(theta_vary)
theta_vary_clipped[np.where(np.isclose(numerator_vary, 0))] = 0
theta_vary_clipped

array([ 0.        ,  1.43170849,  1.37831174,  1.46076858,  0.05288253,
       -1.49171043, -0.01374424,  0.76459593,  1.56722021,  1.5148531 ,
        0.        , -1.5148531 , -1.56722021, -0.76459593,  0.01374424,
        1.49171043, -0.05288253, -1.46076858, -1.37831174, -1.43170849,
        0.        ,  1.43170849,  1.37831174,  1.46076858,  0.05288253,
       -1.49171043, -0.01374424,  0.76459593,  1.56722021,  1.5148531 ,
        0.        , -1.5148531 , -1.56722021, -0.76459593,  0.01374424,
        1.49171043, -0.05288253, -1.46076858, -1.37831174, -1.43170849])