In [1]:
import numpy as np
from astropy import constants as const
from astropy.coordinates import SkyCoord, Angle, EarthLocation, Longitude, spherical_to_cartesian, cartesian_to_spherical
from astropy.time import Time, TimeDelta
from astropy import units
from pyuvdata import utils as uvutils

In [2]:
ra_hrs = 12.1
dec_degs = -42.3
mjd = 55780.1
latitude = Angle('-26d42m11.94986s')
longitude = Angle('116d40m14.93485s')

In [3]:
print(latitude.rad)
print(longitude.rad)

-0.4660608448386394
2.0362898668561042


In [4]:
obs_time = Time(mjd, format='mjd', location = (longitude, latitude))
lst_mean = obs_time.sidereal_time('mean')
lst_apparent = obs_time.sidereal_time('apparent')
print(lst_mean.rad)
print(lst_apparent.rad)

1.8838767933262255
1.8839572321431979


In [5]:
(lst_mean - lst_apparent).to('deg')

<Angle -0.0046088 deg>

In [6]:
mwa_tools_lst_mean = np.float64(1.8838984)

In [7]:
print(Angle(lst_mean.rad - mwa_tools_lst_mean, unit='rad').to('deg'))
print(Angle(lst_apparent.rad - mwa_tools_lst_mean, unit='rad').to('deg'))

-0d00m04.4567s
0d00m12.135s


In [8]:
print((lst_mean - Angle(mwa_tools_lst_mean, unit='rad')).to('deg'))
print((lst_apparent - Angle(mwa_tools_lst_mean, unit='rad')).to('deg'))

-0d00m04.4567s
0d00m12.135s


In [9]:
new_time = obs_time + TimeDelta('-0.8' * units.s)
print(new_time.sidereal_time('apparent').rad)
(new_time.sidereal_time('apparent') - Angle(mwa_tools_lst_mean, unit='rad')).to('deg')
# so to get an apparent LST that matches mwa_tools mean LST, need to add ~ -0.8s

1.8838988952140985


<Angle 2.83736778e-05 deg>

# -> mean LST disagrees by ~4.5 arcseconds (should we use apparent??)

In [10]:
icrs_coord = SkyCoord(ra=Angle(ra_hrs, unit='hr'), dec=Angle(dec_degs, unit='deg'),
                      obstime=obs_time)
icrs_coord

<SkyCoord (ICRS): (ra, dec) in deg
    (181.5, -42.3)>

In [11]:
icrs_coord.ra.rad, icrs_coord.dec.rad

(3.1677725923697078, -0.7382742735936013)

In [12]:
gcrs_coord = icrs_coord.transform_to('gcrs')
gcrs_coord

<SkyCoord (GCRS: obstime=55780.1, obsgeoloc=(0., 0., 0.) m, obsgeovel=(0., 0., 0.) m / s): (ra, dec) in deg
    (181.49525535, -42.3015925)>

In [13]:
gcrs_coord.ra.rad, gcrs_coord.dec.rad

(3.167689782620545, -0.7383020680162412)

In [14]:
# This is the change in ra & dec between icrs & gcrs
print(icrs_coord.ra-gcrs_coord.ra)
print(icrs_coord.dec-gcrs_coord.dec)

0d00m17.0807s
0d00m05.733s


In [15]:
hour_angle_mean = lst_mean.rad - gcrs_coord.ra.rad
hour_angle_apparent = lst_apparent.rad - gcrs_coord.ra.rad

print(hour_angle_mean)
print(hour_angle_apparent)

-1.2838129892943195
-1.2837325504773471


In [16]:
# mwa_tools comp2
# It turns out these are not actually used in the return values at all. So don't worry about them
mwa_tools_comp2_ra = 3.1703987
mwa_tools_comp2_dec = -0.73946297

In [17]:
# compare mwa_tools comp2 to gcrs
print(Angle(gcrs_coord.ra.rad - mwa_tools_comp2_ra, unit='rad').to_string(unit=units.degree, sep=('deg', 'm', 's')))
print(Angle(gcrs_coord.dec.rad - mwa_tools_comp2_dec, unit='rad').to_string(unit=units.degree, sep=('deg', 'm', 's')))

-0deg09m18.7543s
0deg03m59.4532s


In [18]:
# mwa_tools comp3
mwa_tools_comp3_ra = 3.1676898
mwa_tools_comp3_dec = -0.73830205

In [19]:
# compare mwa_tools comp3 to gcrs
print(Angle(gcrs_coord.ra.rad - mwa_tools_comp3_ra, unit='rad').to_string(unit=units.degree, sep=('deg', 'm', 's')))
print(Angle(gcrs_coord.dec.rad - mwa_tools_comp3_dec, unit='rad').to_string(unit=units.degree, sep=('deg', 'm', 's')))

-0deg00m00.0036s
-0deg00m00.0037s


# -> mwa_tools ra_aber/dec_aber (calc3) agrees with GCRS, meaning that it accounts for aberration but not nutation or precession

In [20]:
# The frame radio astronomers call the apparent or current epoch is the
# "true equator & equinox" frame, notated E_gamma in the USNO circular
# astropy doesn't have this frame but it's pretty easy to adapt the CIRS frame
# by modifying the ra to reflect the difference between
# GAST (Grenwich Apparent Sidereal Time) and the earth rotation angle (theta)
def egamma_to_cirs_ra(egamma_ra, time):
    from astropy import _erfa as erfa
    from astropy.coordinates.builtin_frames.utils import get_jd12
    era = erfa.era00(*get_jd12(time, 'ut1'))
    theta_earth = Angle(era, unit='rad')

    assert(isinstance(time, Time))
    assert(isinstance(egamma_ra, Angle))
    gast = time.sidereal_time('apparent', longitude=0)
    cirs_ra = egamma_ra - (gast-theta_earth)
    return cirs_ra

def cirs_to_egamma_ra(cirs_ra, time):
    from astropy import _erfa as erfa
    from astropy.coordinates.builtin_frames.utils import get_jd12
    era = erfa.era00(*get_jd12(time, 'ut1'))
    theta_earth = Angle(era, unit='rad')

    assert(isinstance(time, Time))
    assert(isinstance(cirs_ra, Angle))
    gast = time.sidereal_time('apparent', longitude=0)
    egamma_ra = cirs_ra + (gast-theta_earth)
    return egamma_ra

In [21]:
# now get equivilents of lst, lat in GCRS (rather than precessed) frame:
# effectively current zenith "unprecessed" to J2000 but not undoing aberration
# mwa_tools calls these "lmst2000" and "newarrlat"
# also need gcrs hour angle (ha_gcrs), what they call "ha2000" which is ("lmst2000" - apparent ra)

loc_obj = EarthLocation.from_geodetic(lon=longitude, lat=latitude)

# use CIRS but with a different ra to account for the difference between LST & earth's rotation angle
cirs_ra = egamma_to_cirs_ra(obs_time.sidereal_time('apparent'), obs_time)

assert(cirs_to_egamma_ra(cirs_ra, obs_time) == obs_time.sidereal_time('apparent'))

egamma_zenith_coord = SkyCoord(ra=cirs_ra, dec=latitude, frame='cirs',
                               obstime=obs_time, location = loc_obj)
egamma_zenith_coord

<SkyCoord (CIRS: obstime=55780.1): (ra, dec) in deg
    (107.78961179, -26.70331941)>

In [22]:
# check where it is in altaz (should be near zenith):
egamma_zenith_altaz = egamma_zenith_coord.transform_to('altaz')
egamma_zenith_altaz

<SkyCoord (AltAz: obstime=55780.1, location=(-2559302.5737783727, 5095070.526830904, -2848887.400942108) m, pressure=0.0 hPa, temperature=0.0 deg_C, relative_humidity=0, obswl=1.0 micron): (az, alt) in deg
    (28.60357927, 89.99985796)>

In [23]:
(egamma_zenith_altaz.alt - Angle('90d')).to('deg')

<Angle -0.00014204 deg>

In [24]:
gcrs_zenith = egamma_zenith_altaz.transform_to('gcrs')
gcrs_zenith

<SkyCoord (GCRS: obstime=55780.1, obsgeoloc=(0., 0., 0.) m, obsgeovel=(0., 0., 0.) m / s): (ra, dec) in deg
    (107.82139246, -26.68249473)>

In [25]:
print(gcrs_zenith.ra.rad)
print(gcrs_zenith.dec.rad)

1.8818383024300602
-0.4656973857576238


In [26]:
# This is the change between egamma & gcrs
print(gcrs_zenith.ra - lst_apparent)
print(gcrs_zenith.dec - egamma_zenith_coord.dec)

-0d07m17.0606s
0d01m14.9688s


In [27]:
ha_gcrs = Longitude(gcrs_zenith.ra - gcrs_coord.ra)
ha_gcrs

<Longitude 286.3261371 deg>

In [28]:
ha_gcrs.rad

4.9973338269891014

In [29]:
# for these, I used the apparent lst (and aberration corrected ra/decs) from this notebook,
# so that's not a source of error
mwa_tools_comp4_newarrlat = -0.46569739
mwa_tools_comp4_lmst2000 = 1.8818386
mwa_tools_comp4_ha2000 = 4.9973341

In [30]:
# This is what the MWA tools code gives as the change between precessed & not
print(Angle(lst_apparent.rad - mwa_tools_comp4_lmst2000, unit='rad').to('deg'))
print(Angle(latitude.rad - mwa_tools_comp4_newarrlat, unit='rad').to('deg'))

0d07m16.9992s
-0d01m14.9679s


In [31]:
print(Angle(gcrs_zenith.ra.rad - mwa_tools_comp4_lmst2000, unit='rad').to('deg'))
print(Angle(gcrs_zenith.dec.rad - mwa_tools_comp4_newarrlat, unit='rad').to('deg'))
print(Angle(ha_gcrs.rad - mwa_tools_comp4_ha2000, unit='rad').to('deg'))

-0d00m00.0614s
0d00m00.0009s
-0d00m00.0563s


# => Egamma -> CIRS -> CGRS agrees with computation4

In [32]:
# An undocumented feature lets you get the rotation matrix for some Astropy transforms
from astropy import coordinates
from astropy.coordinates.builtin_frames import icrs_fk5_transforms
fk5 = coordinates.FK5()
icrs_fk5_transforms.icrs_to_fk5(None, fk5)

array([[ 1.00000000e+00, -1.11022333e-07, -4.41180450e-08],
       [ 1.11022337e-07,  1.00000000e+00,  9.64779225e-08],
       [ 4.41180343e-08, -9.64779274e-08,  1.00000000e+00]])

In [33]:
# # But not for the ones we want -- this errors:
# from astropy import coordinates
# from astropy.coordinates.builtin_frames import icrs_cirs_transforms
# cirs = coordinates.CIRS(obstime=Time(mjd, format='mjd'))
# icrs_cirs_transforms.icrs_to_cirs(None, cirs)

In [34]:
# now define an antenna position to work on uvw rotation
# the positions used in the mwa_tools code are the same as those used in uvfits antenna positions:
# relative to the array center (expressed in ITRS), but rotated so that the x axis goes through the meridian

array_center_xyz = np.array([-2559454.08, 5095372.14, -2849057.18])

# in east/north/up frame (relative to array center) in meters: (Nants, 3)
xyz_ants = np.array([[-037.91, 0140.52, 0000.66],[-101.94, 0156.41, 0001.24]])
print(xyz_ants.shape)

lat_lon_alt = uvutils.LatLonAlt_from_XYZ(array_center_xyz)
print(Angle(lat_lon_alt[0]*units.rad).to('deg') - latitude)
print(Angle(lat_lon_alt[1]*units.rad).to('deg') - longitude)
ant_xyz_abs = uvutils.ECEF_from_ENU(xyz_ants.T, lat_lon_alt[0], lat_lon_alt[1], lat_lon_alt[2]).T

ant_xyz_rel_itrs = ant_xyz_abs - array_center_xyz
ant_xyz_rel_rot = uvutils.rotECEF_from_ECEF(ant_xyz_rel_itrs, lat_lon_alt[1])

(2, 3)
0d00m00.0001s
0d00m00.0001s


In [35]:
print(ant_xyz_rel_rot)

[[  63.73518635  -37.91        125.23630472]
 [  71.39382794 -101.94        139.17092739]]


In [36]:
egamma_zenith_xyz = spherical_to_cartesian(1, egamma_zenith_coord.dec, egamma_zenith_coord.ra)
egamma_zenith_xyz

(<Quantity -0.27293726>, <Quantity 0.85062987>, <Quantity -0.44937075>)

In [37]:
egamma_ant_spherical = cartesian_to_spherical(ant_xyz_rel_rot[:, 0], ant_xyz_rel_rot[:, 1], ant_xyz_rel_rot[:, 2])
egamma_ant_spherical

(<Quantity [145.54543655, 186.70133717]>,
 <Latitude [1.03617555, 0.84116482] rad>,
 <Longitude [5.7465945 , 5.32335079] rad>)

In [38]:
cirs_ant_ra = egamma_to_cirs_ra(egamma_ant_spherical[2], obs_time)

cirs_ant_xyz = spherical_to_cartesian(egamma_ant_spherical[0], egamma_ant_spherical[1], cirs_ant_ra)
cirs_ant_xyz

(<Quantity [63.63360223, 71.12102561]>,
 <Quantity [ -38.08026714, -102.13051446]>,
 <Quantity [125.23630472, 139.17092739]>)

In [39]:
cirs_ant_coord = SkyCoord(x=cirs_ant_xyz[0]*units.m, y=cirs_ant_xyz[1]*units.m, z=cirs_ant_xyz[2]*units.m,
                          representation = 'cartesian', frame='cirs',
                          obstime=obs_time)
cirs_ant_coord

<SkyCoord (CIRS: obstime=55780.1): (x, y, z) in m
    [(63.63360223,  -38.08026714, 125.23630472),
     (71.12102561, -102.13051446, 139.17092739)]>

In [40]:
gcrs_ant_coord = cirs_ant_coord.transform_to('gcrs')
gcrs_ant_coord.representation = 'cartesian'
gcrs_ant_coord

<SkyCoord (GCRS: obstime=55780.1, obsgeoloc=(0., 0., 0.) m, obsgeovel=(0., 0., 0.) m / s): (x, y, z) in m
    [(63.77899211,  -38.08136563, 125.16197688),
     (71.28260457, -102.13175108, 139.08732594)]>

In [41]:
mwa_tools_precxyz_xprec = 71.286688
mwa_tools_precxyz_yprec = -102.13304
mwa_tools_precxyz_zprec = 139.08429

In [42]:
# this is how much the input to output changes in mwa_tools (precession + nutation effect)
print(mwa_tools_precxyz_xprec - ant_xyz_rel_rot[1, 0])
print(mwa_tools_precxyz_yprec - ant_xyz_rel_rot[1, 1])
print(mwa_tools_precxyz_zprec - ant_xyz_rel_rot[1, 2])

-0.1071399426444799
-0.1930399991369427
-0.0866373932501574


In [43]:
# This tests agreement between this notebook & mwa_tools
print((gcrs_ant_coord.x[1] - mwa_tools_precxyz_xprec*units.m).to('mm'))
print((gcrs_ant_coord.y[1] - mwa_tools_precxyz_yprec*units.m).to('mm'))
print((gcrs_ant_coord.z[1] - mwa_tools_precxyz_zprec*units.m).to('mm'))

-4.083433813732995 mm
1.2889244154763446 mm
3.035939423682521 mm


# The precessed positions match to < 5mm

In [44]:
# try something else. Define antennas in ITRS frame. Then rotate them to GCRS
array_center_coord = SkyCoord(x=array_center_xyz[0]*units.m,
                              y=array_center_xyz[1]*units.m,
                              z=array_center_xyz[2]*units.m,
                              representation = 'cartesian', frame='itrs', obstime=obs_time)
print(array_center_coord)
itrs_coord = SkyCoord(x=ant_xyz_abs[:, 0]*units.m, y=ant_xyz_abs[:, 1]*units.m, z=ant_xyz_abs[:, 2]*units.m,
                      representation = 'cartesian', frame='itrs', obstime=obs_time)
itrs_coord

<SkyCoord (ITRS: obstime=55780.1): (x, y, z) in m
    (-2559454.08, 5095372.14, -2849057.18)>


<SkyCoord (ITRS: obstime=55780.1): (x, y, z) in m
    [(-2559448.81204191, 5095446.11020141, -2848931.94369528),
     (-2559395.03251243, 5095481.69471912, -2848918.00907261)]>

In [45]:
print(itrs_coord.x - array_center_coord.x)
print(itrs_coord.y - array_center_coord.y)
print(itrs_coord.z - array_center_coord.z)

[ 5.26795809 59.04748757] m
[ 73.97020141 109.55471912] m
[125.23630472 139.17092739] m


In [46]:
gcrs_array_center = array_center_coord.transform_to('gcrs')
print(gcrs_array_center)
gcrs_from_itrs_coord = itrs_coord.transform_to('gcrs')
gcrs_from_itrs_coord

<SkyCoord (GCRS: obstime=55780.1, obsgeoloc=(0., 0., 0.) m, obsgeovel=(0., 0., 0.) m / s): (ra, dec, distance) in (deg, deg, m)
    (107.82119261, -26.52844312, 6374225.38409957)>


<SkyCoord (GCRS: obstime=55780.1, obsgeoloc=(0., 0., 0.) m, obsgeovel=(0., 0., 0.) m / s): (ra, dec, distance) in (deg, deg, m)
    [(107.82081001, -26.52718048, 6374226.42389492),
     (107.82016655, -26.52703837, 6374227.04771532)]>

In [47]:
print(gcrs_array_center)
print(gcrs_array_center.cartesian)
print(gcrs_from_itrs_coord)
print(gcrs_from_itrs_coord.cartesian)

<SkyCoord (GCRS: obstime=55780.1, obsgeoloc=(0., 0., 0.) m, obsgeovel=(0., 0., 0.) m / s): (ra, dec, distance) in (deg, deg, m)
    (107.82119261, -26.52844312, 6374225.38409957)>
(-1745419.47561659, 5429444.58424123, -2846996.94557109) m
<SkyCoord (GCRS: obstime=55780.1, obsgeoloc=(0., 0., 0.) m, obsgeovel=(0., 0., 0.) m / s): (ra, dec, distance) in (deg, deg, m)
    [(107.82081001, -26.52718048, 6374226.42389492),
     (107.82016655, -26.52703837, 6374227.04771532)]>
[(-1745402.70537897, 5429516.85350522, -2846871.72816737),
 (-1745344.06078713, 5429543.70843817, -2846857.86147819)] m


In [48]:
gcrs_rel = (gcrs_from_itrs_coord.cartesian - gcrs_array_center.cartesian).get_xyz().T

print(gcrs_rel)

[[ 16.77023762  72.26926399 125.21740372]
 [ 75.41482945  99.12419693 139.08409291]] m


In [49]:
gcrs_lat_lon_alt = uvutils.LatLonAlt_from_XYZ(gcrs_array_center.cartesian.get_xyz().value)
print(gcrs_lat_lon_alt[1])
gcrs_array_center_spherical = gcrs_array_center.spherical
print(gcrs_array_center_spherical.lon - Angle(gcrs_lat_lon_alt[1]*units.rad))
print(gcrs_zenith.ra - Angle(gcrs_lat_lon_alt[1]*units.rad))

zenith_coord = SkyCoord(alt=Angle(90 * units.deg), az=Angle(0 * units.deg),
                        obstime=obs_time, frame='altaz', location=loc_obj)
new_gcrs_zenith = zenith_coord.transform_to('gcrs')
print(new_gcrs_zenith.ra - Angle(gcrs_lat_lon_alt[1]*units.rad))

gcrs_rel_rot = uvutils.rotECEF_from_ECEF(gcrs_rel.value, gcrs_lat_lon_alt[1])

print(gcrs_rel_rot)

1.8818348144562813
0d00m00s
0d00m00.7194s
0d00m00.4461s
[[  63.66902558  -38.08336341  125.21740372]
 [  71.28733004 -102.13285218  139.08409291]]


In [50]:
print((gcrs_rel_rot[:, 0]*units.m - gcrs_ant_coord.x).to('mm'))
print((gcrs_rel_rot[:, 1]*units.m - gcrs_ant_coord.y).to('mm'))
print((gcrs_rel_rot[:, 2]*units.m - gcrs_ant_coord.z).to('mm'))

[-109.96652825    4.72547333] mm
[-1.99777694 -1.10110753] mm
[55.42683999 -3.23303321] mm


In [51]:
print(((gcrs_rel_rot[1, 0] - mwa_tools_precxyz_xprec)*units.m).to('mm'))
print(((gcrs_rel_rot[1, 1] - mwa_tools_precxyz_yprec)*units.m).to('mm'))
print(((gcrs_rel_rot[1, 2] - mwa_tools_precxyz_zprec)*units.m).to('mm'))

0.6420395208408536 mm
0.187816887404324 mm
-0.19709378943844058 mm


# Starting from ITRS does even better: positions match to < 1mm

In [52]:
def mwatools_calcuvw(ha, dec, xyz):
    if xyz.ndim == 1:
        xyz = xyz[np.newaxis, :]
    
    sh = np.sin(ha);
    sd = np.sin(dec);
    ch = np.cos(ha);
    cd = np.cos(dec);

    u = sh * xyz[:, 0] + ch * xyz[:, 1];
    v = -sd * ch * xyz[:, 0] + sd * sh * xyz[:, 1] + cd * xyz[:, 2];
    w =  cd * ch * xyz[:, 0] - cd * sh * xyz[:, 1] + sd * xyz[:, 2];
    return np.array([u, v, w]).T
# matching things up, this code expects relative xyz locations in the 'rotated ECEF' frame expected by uvfits

In [53]:
def calc_uvw_norot(ra, dec, longitude, xyz):
    # same as mwatools_calcuvw but using relative xyz locations in ECEF not rotated frame
    if xyz.ndim == 1:
        xyz = xyz[np.newaxis, :]
    
    ha = Longitude(longitude*units.rad - ra*units.rad).rad
    print(ha)
    
    rot_xyz = uvutils.rotECEF_from_ECEF(xyz, longitude)
    print(rot_xyz)
    
    sr = np.sin(ha);
    sd = np.sin(dec);
    cr = np.cos(ha);
    cd = np.cos(dec);

    u = sr * rot_xyz[:, 0] + cr * rot_xyz[:, 1];
    v = -sd * cr * rot_xyz[:, 0] + sd * sr * rot_xyz[:, 1] + cd * rot_xyz[:, 2];
    w =  cd * cr * rot_xyz[:, 0] - cd * sr * rot_xyz[:, 1] + sd * rot_xyz[:, 2];
    return np.array([u, v, w]).T
 

In [54]:
def phase_uvw(ra, dec, xyz):
    # This code expects relative xyz locations in the same frame that ra/dec are in (e.g. icrs or gcrs)
    
    if xyz.ndim == 1:
        xyz = xyz[np.newaxis, :]

    uvw = np.zeros_like(xyz)
    uvw[:, 0] = (-np.sin(ra) * xyz[:, 0]
                 + np.cos(ra) * xyz[:, 1])
    uvw[:, 1] = (-np.sin(dec) * np.cos(ra) * xyz[:, 0]
                 - np.sin(dec) * np.sin(ra) * xyz[:, 1]
                 + np.cos(dec) * xyz[:, 2])
    uvw[:, 2] = (np.cos(dec) * np.cos(ra) * xyz[:, 0]
                 + np.cos(dec) * np.sin(ra) * xyz[:, 1]
                 + np.sin(dec) * xyz[:, 2])
    return(uvw)

In [55]:
print(ha_gcrs.rad)
print(gcrs_coord.ra.rad)
print(gcrs_coord.dec.rad)

4.9973338269891014
3.167689782620545
-0.7383020680162412


In [56]:
gcrs_uvw = mwatools_calcuvw(ha_gcrs.rad, gcrs_coord.dec.rad, gcrs_rel_rot)
print(ha_gcrs.rad)
print(gcrs_rel_rot)
gcrs_uvw

4.9973338269891014
[[  63.66902558  -38.08336341  125.21740372]
 [  71.28733004 -102.13285218  139.08409291]]


array([[ -71.8071152 ,   80.06022048,  -98.06928615],
       [ -97.12282891,   50.38831246, -151.27974713]])

In [57]:
longitude_use = gcrs_zenith.ra.rad
gcrs_uvw_mod1 = calc_uvw_norot(gcrs_coord.ra.rad, gcrs_coord.dec.rad, longitude_use, gcrs_rel.value)
print(gcrs_uvw_mod1)
longitude_use = gcrs_lat_lon_alt[1]
gcrs_uvw_mod2 = calc_uvw_norot(gcrs_coord.ra.rad, gcrs_coord.dec.rad, longitude_use, gcrs_rel.value)
print(gcrs_uvw_mod2)
longitude_use = new_gcrs_zenith.ra.rad
gcrs_uvw_mod3 = calc_uvw_norot(gcrs_coord.ra.rad, gcrs_coord.dec.rad, longitude_use, gcrs_rel.value)
print(gcrs_uvw_mod3)

4.9973338269891014
[[  63.66889275  -38.08358549  125.21740372]
 [  71.2869738  -102.13310083  139.08409291]]
[[ -71.80705015   80.06005191  -98.06947139]
 [ -97.12255694   50.38808446 -151.27999768]]
4.997330339015322
[[  63.66902558  -38.08336341  125.21740372]
 [  71.28733004 -102.13285218  139.08409291]]
[[ -71.80705015   80.06005191  -98.06947139]
 [ -97.12255694   50.38808446 -151.27999768]]
4.997332501661898
[[  63.66894322  -38.0835011   125.21740372]
 [  71.28710916 -102.13300635  139.08409291]]
[[ -71.80705015   80.06005191  -98.06947139]
 [ -97.12255694   50.38808446 -151.27999768]]


In [58]:
print(((gcrs_uvw_mod1 - gcrs_uvw)*units.m).to('mm'))
print(((gcrs_uvw_mod2 - gcrs_uvw)*units.m).to('mm'))
print(((gcrs_uvw_mod3 - gcrs_uvw)*units.m).to('mm'))
# This means that the difference comes because we're using different longitudes to calculate ha & do the ECEF rotation.
# (gcrs_zenith for the ha & gcrs_lat_lon_alt[1] for the rotation)
# That difference is wrong, we should use the same one.

[[ 0.06505144 -0.16856869 -0.18524422]
 [ 0.27197665 -0.22799763 -0.25055213]] mm
[[ 0.06505144 -0.16856869 -0.18524422]
 [ 0.27197665 -0.22799763 -0.25055213]] mm
[[ 0.06505144 -0.16856869 -0.18524422]
 [ 0.27197665 -0.22799763 -0.25055213]] mm


In [59]:
gcrs_uvw_new = phase_uvw(gcrs_coord.ra.rad, gcrs_coord.dec.rad, gcrs_rel.value)
print(gcrs_coord.ra, gcrs_coord.dec)
gcrs_uvw_new

181d29m42.9193s -42d18m05.733s


array([[ -71.80705015,   80.06005191,  -98.06947139],
       [ -97.12255694,   50.38808446, -151.27999768]])

In [60]:
print(((gcrs_uvw_new - gcrs_uvw)*units.m).to('mm'))
print(((gcrs_uvw_new - gcrs_uvw_mod1)*units.m).to('mm'))
# So phase_uvw works the same as calc_uvw_norot which would match mwatools_calcuvw if we used the same longitude.
# we'll use phase_uvw in pyuvdata because it's simplest

[[ 0.06505144 -0.16856869 -0.18524422]
 [ 0.27197665 -0.22799763 -0.25055213]] mm
[[ 0.00000000e+00  1.42108547e-11  1.42108547e-11]
 [-2.84217094e-11  1.42108547e-11  2.84217094e-11]] mm


In [61]:
mwa_tools_calcuvw_u = -97.122828
mwa_tools_calcuvw_v = 50.388281
mwa_tools_calcuvw_w = -151.27976

In [62]:
print(((gcrs_uvw[1, 0] - mwa_tools_calcuvw_u)*units.m).to('mm'))
print(((gcrs_uvw[1, 1] - mwa_tools_calcuvw_v)*units.m).to('mm'))
print(((gcrs_uvw[1, 2] - mwa_tools_calcuvw_w)*units.m).to('mm'))

-0.000913630060495052 mm
0.031455671035018895 mm
0.012874193629386355 mm


In [63]:
print(((gcrs_uvw_new[1, 0] - mwa_tools_calcuvw_u)*units.m).to('mm'))
print(((gcrs_uvw_new[1, 1] - mwa_tools_calcuvw_v)*units.m).to('mm'))
print(((gcrs_uvw_new[1, 2] - mwa_tools_calcuvw_w)*units.m).to('mm'))

0.27106302223955936 mm
-0.196541958501939 mm
-0.23767793922502278 mm


# =>These match exactly, as expected because I copied the code

In [64]:
# Now redo it all but go to icrs instead of gcrs to include abberation
icrs_zenith = egamma_zenith_altaz.transform_to('icrs')
ha_icrs = Longitude(icrs_zenith.ra - icrs_coord.ra)
icrs_array_center = array_center_coord.transform_to('icrs')
icrs_array_center.representation = 'cartesian'
icrs_from_itrs_coord = itrs_coord.transform_to('icrs')
icrs_from_itrs_coord.representation = 'cartesian'

icrs_rel = (np.array([icrs_from_itrs_coord.x.value, icrs_from_itrs_coord.y.value, icrs_from_itrs_coord.z.value]).T
            - np.array([icrs_array_center.x.value, icrs_array_center.y.value, icrs_array_center.z.value]))
icrs_rel_rot = uvutils.rotECEF_from_ECEF(icrs_rel, gcrs_lat_lon_alt[1])
icrs_uvw = mwatools_calcuvw(ha_icrs.rad, icrs_coord.dec.rad, icrs_rel_rot)
icrs_uvw

array([[ -71.81674489,   80.06394052,  -98.06404622],
       [ -97.13904509,   50.39209463, -151.27324229]])

In [65]:
(gcrs_uvw*units.m - icrs_uvw*units.m).to('mm')

<Quantity [[ 9.62968499, -3.72004541, -5.23992454],
           [16.21617209, -3.78217843, -6.50483438]] mm>

# => 10's of mm scale for itrs vs gcrs

In [66]:
# try to figure out what zenith uvws are in current epoch frame -- can they be calculated from ENU?
itrs_lat_lon_alt = uvutils.LatLonAlt_from_XYZ(np.array([array_center_coord.x.value,
                                                        array_center_coord.y.value,
                                                        array_center_coord.z.value]))
itrs_rel = (np.array([itrs_coord.x.value, itrs_coord.y.value, itrs_coord.z.value]).T
            - np.array([array_center_coord.x.value, array_center_coord.y.value, array_center_coord.z.value]))
itrs_rel_rot = uvutils.rotECEF_from_ECEF(itrs_rel, itrs_lat_lon_alt[1])

print(itrs_rel_rot)
print(xyz_ants)

itrs_uvw = mwatools_calcuvw(0, latitude, itrs_rel_rot)
print(itrs_uvw)
print(itrs_uvw - xyz_ants)

# good. So this means that the mwatools calculator,
# which takes coordinates in the weird relative but rotated ECEF frame,
# gives the same answer for zenith phasing as just using ENU positions

[[  63.73518635  -37.91        125.23630472]
 [  71.39382794 -101.94        139.17092739]]
[[ -37.91  140.52    0.66]
 [-101.94  156.41    1.24]]
[[ -37.91        140.52          0.65999992]
 [-101.94        156.41          1.23999991]]
[[-8.33622948e-10 -5.44986278e-10 -7.88458329e-08]
 [-8.63053629e-10  5.80087089e-11 -8.74636734e-08]]


In [67]:
# for phasing the data:
# mwa_tools c code: phase = cexp(I*w*k[chan_ind])
# k[chan_ind] = freq/(VLIGHT/1e6)
# corrected_vis = vis*phase
freq = 150 * units.MHz

bl_uvw = gcrs_uvw[1, :] - gcrs_uvw[0, :]

phase = np.exp(1j * bl_uvw[2]*units.m *freq.to('1/s') / const.c)
phase

<Quantity 0.0798037-0.9968106j>

# Now work out how to "unphase" to drift

In [68]:
def mwatools_calcuvw_unphase(ha, dec, uvw):
    if uvw.ndim == 1:
        uvw = uvw[np.newaxis, :]

    sh = np.sin(ha)
    sd = np.sin(dec)
    ch = np.cos(ha)
    cd = np.cos(dec)

    x = sh * uvw[:, 0] - sd * ch * uvw[:, 1] + cd * ch * uvw[:, 2]
    y = ch * uvw[:, 0] + sd * sh * uvw[:, 1] - cd * sh * uvw[:, 2]
    z = cd * uvw[:, 1] + sd * uvw[:, 2]
    return np.array([x, y, z]).T

In [69]:
def unphase_uvw(ra, dec, uvw):
    # This code expects uvw locations in the same frame that ra/dec are in (e.g. icrs or gcrs)
    
    if uvw.ndim == 1:
        uvw = uvw[np.newaxis, :]

    xyz = np.zeros_like(uvw)
    xyz[:, 0] = (-np.sin(ra) * uvw[:, 0]
                 -np.sin(dec) * np.cos(ra) * uvw[:, 1]
                 +np.cos(dec) * np.cos(ra) * uvw[:, 2])
                
    xyz[:, 1] = (np.cos(ra) * uvw[:, 0]
                 - np.sin(dec) * np.sin(ra) * uvw[:, 1]
                 + np.cos(dec) * np.sin(ra) * uvw[:, 2])
                 
    xyz[:, 2] = (np.cos(dec) * uvw[:, 1]
                + np.sin(dec) * uvw[:, 2])
                     
    return(xyz)

In [70]:
# start with gcrs_uvw

# first unphase to get positions in rotECEF frame
uvw_rot_positions = mwatools_calcuvw_unphase(ha_gcrs.rad,
                                             gcrs_coord.dec.rad,
                                             gcrs_uvw)
print(uvw_rot_positions)
print(gcrs_rel_rot)
print(uvw_rot_positions - gcrs_rel_rot)

[[  63.66902558  -38.08336341  125.21740372]
 [  71.28733004 -102.13285218  139.08409291]]
[[  63.66902558  -38.08336341  125.21740372]
 [  71.28733004 -102.13285218  139.08409291]]
[[ 0.00000000e+00  0.00000000e+00  1.42108547e-14]
 [ 0.00000000e+00 -1.42108547e-14  0.00000000e+00]]


In [71]:
# next rotate them so they can be added to telescope location in frame
uvw_rel_positions = uvutils.ECEF_from_rotECEF(uvw_rot_positions,
                                              gcrs_lat_lon_alt[1])

uvw_rel_pos_unphase = unphase_uvw(gcrs_coord.ra.rad, gcrs_coord.dec.rad,
                                  gcrs_uvw)

print(uvw_rel_positions)
print(gcrs_rel)
print(uvw_rel_positions - gcrs_rel.value)
print(uvw_rel_pos_unphase)
print(uvw_rel_positions - uvw_rel_pos_unphase)

[[ 16.77023762  72.26926399 125.21740372]
 [ 75.41482945  99.12419693 139.08409291]]
[[ 16.77023762  72.26926399 125.21740372]
 [ 75.41482945  99.12419693 139.08409291]] m
[[7.10542736e-15 0.00000000e+00 1.42108547e-14]
 [1.42108547e-14 1.42108547e-14 0.00000000e+00]]
[[ 16.76998555  72.26932248 125.21740372]
 [ 75.41448371  99.12445998 139.08409291]]
[[ 2.52073400e-04 -5.84937095e-05  0.00000000e+00]
 [ 3.45743059e-04 -2.63044345e-04  0.00000000e+00]]


In [72]:
gcrs_uvw_coord = SkyCoord(x=uvw_rel_positions[:, 0] * units.m + gcrs_array_center.cartesian.x,
                          y=uvw_rel_positions[:, 1] * units.m + gcrs_array_center.cartesian.y,
                          z=uvw_rel_positions[:, 2] * units.m + gcrs_array_center.cartesian.z,
                          representation='cartesian',
                          frame='gcrs', obstime=obs_time)

print(gcrs_uvw_coord)
print(gcrs_from_itrs_coord)
print(gcrs_uvw_coord.cartesian - gcrs_from_itrs_coord.cartesian)

<SkyCoord (GCRS: obstime=55780.1, obsgeoloc=(0., 0., 0.) m, obsgeovel=(0., 0., 0.) m / s): (x, y, z) in m
    [(-1745402.70537897, 5429516.85350522, -2846871.72816737),
     (-1745344.06078713, 5429543.70843817, -2846857.86147819)]>
<SkyCoord (GCRS: obstime=55780.1, obsgeoloc=(0., 0., 0.) m, obsgeovel=(0., 0., 0.) m / s): (ra, dec, distance) in (deg, deg, m)
    [(107.82081001, -26.52718048, 6374226.42389492),
     (107.82016655, -26.52703837, 6374227.04771532)]>
[(0., 0., 0.), (0., 0., 0.)] m


In [73]:
itrs_uvw_coord = gcrs_uvw_coord.transform_to('itrs')
itrs_uvw_coord.representation = 'cartesian'

print(itrs_uvw_coord)
print(itrs_coord)
print((itrs_uvw_coord.cartesian - itrs_coord.cartesian).get_xyz().to('mm'))

<SkyCoord (ITRS: obstime=55780.1): (x, y, z) in m
    [(-2559448.81203606, 5095446.11019442, -2848931.94367792),
     (-2559395.03255611, 5095481.69466939, -2848918.00908438)]>
<SkyCoord (ITRS: obstime=55780.1): (x, y, z) in m
    [(-2559448.81204191, 5095446.11020141, -2848931.94369528),
     (-2559395.03251243, 5095481.69471912, -2848918.00907261)]>
[[ 0.00584684 -0.04367111]
 [-0.00698864 -0.04972704]
 [ 0.01735194 -0.01177331]] mm


# Working with uvws (vs antenna positions)

In [74]:
antenna_rel = np.array([[-5.61445218e+00, -3.22826900e+01,  1.01146299e+01],
                        [-1.58438792e+01, -6.21817931e+00,  1.01146299e+01],
                        [-1.25728548e-07,  3.13855708e-07, -1.21071935e-08]])
telescope_loc = np.array([ 5109342.76037543,  2005241.90402741, -3239939.46926403])
antenna_ecef = antenna_rel + telescope_loc
print(antenna_rel[0, :] + telescope_loc)
print(antenna_ecef)

[ 5109337.14592325  2005209.62133741 -3239929.35463413]
[[ 5109337.14592325  2005209.62133741 -3239929.35463413]
 [ 5109326.91649623  2005235.6858481  -3239929.35463413]
 [ 5109342.7603753   2005241.90402772 -3239939.46926404]]


In [75]:
lat_lon_alt = uvutils.LatLonAlt_from_XYZ(telescope_loc)
antenna_enu = uvutils.ENU_from_ECEF(antenna_ecef.T, *lat_lon_alt).T
print(antenna_enu)

[[-2.79999979e+01  3.45201272e-08 -1.97989899e+01]
 [ 1.91888926e-07  4.94729520e-08 -1.97989899e+01]
 [ 3.38093824e-07 -4.41559063e-09 -1.38232040e-10]]


In [76]:
antenna_rot_ecef = uvutils.rotECEF_from_ECEF(antenna_rel, lat_lon_alt[1])
phase_ant = mwatools_calcuvw(0, lat_lon_alt[0], antenna_rot_ecef)
print(phase_ant)
print('')
phase_ant_simple = phase_uvw(lat_lon_alt[1], lat_lon_alt[0], antenna_rel)
temp = unphase_uvw(lat_lon_alt[1], lat_lon_alt[0], phase_ant_simple)
assert(np.allclose(temp, antenna_rel))

print(phase_ant_simple)
print(phase_ant - phase_ant_simple)

[[-2.79999979e+01  2.74625620e-08 -1.97989899e+01]
 [ 1.92015205e-07  4.19946176e-08 -1.97989899e+01]
 [ 3.38093825e-07 -1.16211809e-08  4.14379671e-09]]

[[-2.79999979e+01  2.74625638e-08 -1.97989899e+01]
 [ 1.92015205e-07  4.19946176e-08 -1.97989899e+01]
 [ 3.38093825e-07 -1.16211809e-08  4.14379671e-09]]
[[ 0.00000000e+00 -1.77635684e-15  0.00000000e+00]
 [ 4.41163240e-16  0.00000000e+00 -3.55271368e-15]
 [ 0.00000000e+00  8.27180613e-24 -1.65436123e-24]]


In [77]:
print(phase_ant-antenna_enu)

[[-1.45050194e-10 -7.05756520e-09  4.69347938e-09]
 [ 1.26278984e-10 -7.47833440e-09  3.98542355e-09]
 [ 4.86039311e-16 -7.20559026e-09  4.28202875e-09]]


In [78]:
uvw_enu = np.array([antenna_enu[1, :] - antenna_enu[0, :],
                    antenna_enu[2, :] - antenna_enu[0, :],
                    antenna_enu[2, :] - antenna_enu[1, :]])
phased_uvw = np.array([phase_ant[1, :] - phase_ant[0, :],
                      phase_ant[2, :] - phase_ant[0, :],
                      phase_ant[2, :] - phase_ant[1, :]])
uvw_ecef = np.array([antenna_ecef[1, :] - antenna_ecef[0, :],
                     antenna_ecef[2, :] - antenna_ecef[0, :],
                     antenna_ecef[2, :] - antenna_ecef[1, :]])

In [79]:
uvw_enu-phased_uvw

array([[-2.71327849e-10,  4.20769197e-10,  7.08055836e-10],
       [-1.45053747e-10,  1.48025065e-10,  4.11450429e-10],
       [ 1.26278498e-10, -2.72744132e-10, -2.96605407e-10]])

In [80]:
# to unphase uvws, treat them like they need to end up in ENU (not ECEF or rotECEF)
# this puts them in rotECEF:
temp_unphase = mwatools_calcuvw_unphase(0, lat_lon_alt[0], phased_uvw)
# now go to ECEF
temp_unphase_ecef = uvutils.ECEF_from_rotECEF(temp_unphase, lat_lon_alt[1]) + telescope_loc
print(uvw_ecef)
# then go to ENU
uvw_unphased = uvutils.ENU_from_ECEF(temp_unphase_ecef.T, *lat_lon_alt).T
print(uvw_unphased)
print(uvw_unphased-phased_uvw)
print('')

phased_uvw_rel_ecef = unphase_uvw(lat_lon_alt[1], lat_lon_alt[0], phased_uvw)
phased_uvw_ecef = phased_uvw_rel_ecef + telescope_loc
uvw_unphased2 = uvutils.ENU_from_ECEF(phased_uvw_ecef.T, *lat_lon_alt).T

print(uvw_unphased2)
print(uvw_unphased2-uvw_unphased)

[[-10.22942702  26.06451069   0.        ]
 [  5.61445205  32.28269031 -10.11462991]
 [ 15.84387907   6.21817962 -10.11462991]]
[[ 2.79999981e+01  2.17155238e-08  2.01345802e-08]
 [ 2.79999983e+01 -3.17301279e-08  1.97989899e+01]
 [ 1.46204899e-07 -4.66829526e-08  1.97989899e+01]]
[[ 6.89190927e-11  7.18346824e-09 -4.31925252e-09]
 [-1.45050194e-10  7.35361504e-09 -3.87057852e-09]
 [ 1.26278978e-10  6.93284585e-09 -4.57863436e-09]]

[[ 2.79999981e+01  2.17155238e-08  2.01345802e-08]
 [ 2.79999983e+01 -3.17301279e-08  1.97989899e+01]
 [ 1.46204899e-07 -4.66829526e-08  1.97989899e+01]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [81]:
# how much do uvws change from itrs enu values if you phase them to zenith in gcrs?
uvw_enu = np.array([antenna_enu[1, :] - antenna_enu[0, :],
                    antenna_enu[2, :] - antenna_enu[0, :],
                    antenna_enu[2, :] - antenna_enu[1, :]])
uvw_enu_ecef = uvutils.ECEF_from_ENU(uvw_enu.T, *lat_lon_alt).T
uvw_enu_rel_ecef = uvw_enu_ecef - telescope_loc
uvw_enu_rel_rot_ecef = uvutils.rotECEF_from_ECEF(uvw_enu_rel_ecef, lat_lon_alt[1])

zenith_coord = SkyCoord(alt=Angle(90 * units.deg), az=Angle(0 * units.deg),
                        obstime=obs_time, frame='altaz', location=EarthLocation.from_geocentric(*telescope_loc, unit='m'))
gcrs_zenith = zenith_coord.transform_to('gcrs')

telescope_loc_itrs = SkyCoord(x=telescope_loc[0] * units.m,
                              y=telescope_loc[1] * units.m,
                              z=telescope_loc[2] * units.m,
                              representation='cartesian',
                              frame='itrs', obstime=obs_time)
telescope_loc_gcrs = telescope_loc_itrs.transform_to('gcrs')
uvw_enu_itrs_coord = SkyCoord(x=uvw_enu_ecef[:, 0] * units.m,
                              y=uvw_enu_ecef[:, 1] * units.m,
                              z=uvw_enu_ecef[:, 2] * units.m,
                              representation='cartesian',
                              frame='itrs', obstime=obs_time)
uvw_enu_gcrs_coord = uvw_enu_itrs_coord.transform_to('gcrs')

print(gcrs_zenith.ra, gcrs_zenith.dec)
print(telescope_loc_gcrs.ra, telescope_loc_gcrs.dec)
print((gcrs_zenith.ra - telescope_loc_gcrs.ra).to('arcsec'), (gcrs_zenith.dec - telescope_loc_gcrs.dec).to('arcsec'))
print('')

# print(uvw_enu_gcrs_coord.cartesian.get_xyz().value.T[:, 0])
uvw_enu_gcrs_rel_ecef = uvw_enu_gcrs_coord.cartesian.get_xyz().value.T - telescope_loc_gcrs.cartesian.get_xyz().value
print(uvw_enu_gcrs_rel_ecef)
uvw_enu_gcrs_rel_rot_ecef = uvutils.rotECEF_from_ECEF(uvw_enu_gcrs_rel_ecef, telescope_loc_gcrs.ra.rad)
print(uvw_enu_gcrs_rel_rot_ecef)


print('')
mwatools_phase_uvws = mwatools_calcuvw(0, gcrs_zenith.dec, uvw_enu_gcrs_rel_rot_ecef)
print(mwatools_phase_uvws)
simple_phase_uvws = phase_uvw(gcrs_zenith.ra, gcrs_zenith.dec, uvw_enu_gcrs_rel_ecef)
print(simple_phase_uvws)
print('')
print(mwatools_phase_uvws - simple_phase_uvws)
print('')
print(uvw_enu - mwatools_phase_uvws)
print(uvw_enu - simple_phase_uvws)



12d33m20.9945s -30d47m11.0173s
12d33m21.1026s -30d37m03.6457s
-0.108091arcsec -607.372arcsec

[[-6.08279595e+00  2.73313135e+01  7.24636298e-03]
 [ 1.05194115e+01  3.10289339e+01 -1.01266519e+01]
 [ 1.66021617e+01  3.69768144e+00 -1.01338906e+01]]
[[ 4.26879564e-03  2.80000194e+01  7.24636298e-03]
 [ 1.70132573e+01  2.80000327e+01 -1.01266519e+01]
 [ 1.70089571e+01  8.28930982e-05 -1.01338906e+01]]

[[ 2.80000194e+01  8.41015169e-03 -4.17269980e-05]
 [ 2.80000327e+01  8.42737964e-03  1.97989881e+01]
 [ 8.28930982e-05  7.69968847e-06  1.97989989e+01]]
[[ 2.80000194e+01  8.40264144e-03 -5.43323614e-05]
 [ 2.80000416e+01  8.41986939e-03  1.97989755e+01]
 [ 9.18064361e-05  7.69966504e-06  1.97989989e+01]]

[[-2.23316832e-09  7.51024809e-06  1.26053634e-05]
 [-8.91558759e-06  7.51025287e-06  1.26053715e-05]
 [-8.91333795e-06  2.34283704e-11  3.93249877e-11]]

[[-2.12401188e-05 -8.41013674e-03  4.17521599e-05]
 [-3.44656822e-05 -8.42741858e-03  1.79320964e-06]
 [-8.27468933e-05 -7.75357701e-