In [14]:
import os

import numpy as np
import pandas as pd
from astropy.time import Time
from astropy.coordinates import EarthLocation, Angle
from astroquery.vizier import Vizier

import pyuvsim

In [2]:
ant_per_side = 6
n_ants = ant_per_side ** 2
dish_size_m = 14
antenna_layout_coords = (np.arange(ant_per_side) - (ant_per_side - 1) / 2) * dish_size_m


In [3]:
antenna_layout_coords

array([-35., -21.,  -7.,   7.,  21.,  35.])

In [4]:
antenna_layout_east, antenna_layout_north = np.meshgrid(antenna_layout_coords, antenna_layout_coords)

In [5]:
antenna_layout_east.flatten()

array([-35., -21.,  -7.,   7.,  21.,  35., -35., -21.,  -7.,   7.,  21.,
        35., -35., -21.,  -7.,   7.,  21.,  35., -35., -21.,  -7.,   7.,
        21.,  35., -35., -21.,  -7.,   7.,  21.,  35., -35., -21.,  -7.,
         7.,  21.,  35.])

In [6]:
antenna_layout_north.flatten()

array([-35., -35., -35., -35., -35., -35., -21., -21., -21., -21., -21.,
       -21.,  -7.,  -7.,  -7.,  -7.,  -7.,  -7.,   7.,   7.,   7.,   7.,
         7.,   7.,  21.,  21.,  21.,  21.,  21.,  21.,  35.,  35.,  35.,
        35.,  35.,  35.])

In [7]:
antenna_layout_df = pd.DataFrame()
antenna_layout_df['Name'] = ['ant' + str(ind) for ind in range(n_ants)]
antenna_layout_df['Number'] = np.arange(n_ants)
antenna_layout_df['BeamID'] = np.zeros(n_ants, dtype=int)
antenna_layout_df['E'] = antenna_layout_east.flatten()
antenna_layout_df['N'] = antenna_layout_north.flatten()
antenna_layout_df['U'] = np.zeros(n_ants)

In [8]:
antenna_layout_df.to_csv('square_grid_layout.csv', sep='\t', index=False)

In [9]:
# download GLEAM catalog
filename = 'gleam_catalog.vot'
if not os.path.isfile(filename):
    Vizier.ROW_LIMIT = -1
    catname = 'VIII/100/gleamegc'
    tab = Vizier.get_catalogs(catname)[0]
    tab.write(filename, format='votable')


In [19]:
obstime = Time(2456528.2532407343, scale='utc', format='jd')

In [21]:
obstime.iso

'2013-08-23 18:04:39.999'

In [15]:
Angle("-26d42m11.94986s").degree

-26.703319405555554

In [16]:
Angle("116d40m14.93485s").degree

116.67081523611111

In [22]:
# Now try running pyuvsim
pyuvsim.uvsim.run_uvsim('square_grid_config.yaml')

Mean of empty slice.
invalid value encountered in double_scalars
No spectral_type specified for GLEAM, using 'flat'.


Nbls: 61
Ntimes: 1
Nfreqs: 1
Nsrcs: 307455
Tasks:  61.0
1.64% completed. 0:00:00.349160  elapsed. 0:00:20.949597 remaining. 

3.28% completed. 0:00:00.370620  elapsed. 0:00:10.933290 remaining. 

4.92% completed. 0:00:00.389618  elapsed. 0:00:07.532613 remaining. 

6.56% completed. 0:00:00.408711  elapsed. 0:00:05.824131 remaining. 

8.20% completed. 0:00:00.425394  elapsed. 0:00:04.764413 remaining. 

9.84% completed. 0:00:00.447121  elapsed. 0:00:04.098608 remaining. 

11.48% completed. 0:00:00.464795  elapsed. 0:00:03.585560 remaining. 

13.11% completed. 0:00:00.482603  elapsed. 0:00:03.197245 remaining. 

14.75% completed. 0:00:00.499838  elapsed. 0:00:02.887954 remaining. 

16.39% completed. 0:00:00.517619  elapsed. 0:00:02.639856 remaining. 

18.03% completed. 0:00:00.534524  elapsed. 0:00:02.429654 remaining. 

19.67% completed. 0:00:00.552872  elapsed. 0:00:02.257560 remaining. 

21.31% completed. 0:00:00.571840  elapsed. 0:00:02.111409 remaining. 

22.95% completed. 0:00:00.5

In [23]:
# Now try running pyuvsim
pyuvsim.uvsim.run_uvsim('square_grid_50mjy_config.yaml')

Mean of empty slice.
invalid value encountered in double_scalars
No spectral_type specified for GLEAM, using 'flat'.


Nbls: 61
Ntimes: 1
Nfreqs: 1
Nsrcs: 283601
Tasks:  61.0
1.64% completed. 0:00:00.328689  elapsed. 0:00:19.721332 remaining. 

3.28% completed. 0:00:00.346359  elapsed. 0:00:10.217591 remaining. 

4.92% completed. 0:00:00.363665  elapsed. 0:00:07.030854 remaining. 

6.56% completed. 0:00:00.378661  elapsed. 0:00:05.395918 remaining. 

8.20% completed. 0:00:00.395790  elapsed. 0:00:04.432846 remaining. 

9.84% completed. 0:00:00.412259  elapsed. 0:00:03.779042 remaining. 

11.48% completed. 0:00:00.427795  elapsed. 0:00:03.300132 remaining. 

13.11% completed. 0:00:00.444338  elapsed. 0:00:02.943740 remaining. 

14.75% completed. 0:00:00.460917  elapsed. 0:00:02.663076 remaining. 

16.39% completed. 0:00:00.475911  elapsed. 0:00:02.427146 remaining. 

18.03% completed. 0:00:00.493442  elapsed. 0:00:02.242918 remaining. 

19.67% completed. 0:00:00.509252  elapsed. 0:00:02.079445 remaining. 

21.31% completed. 0:00:00.524021  elapsed. 0:00:01.934847 remaining. 

22.95% completed. 0:00:00.5

In [24]:
# Now try running pyuvsim
pyuvsim.uvsim.run_uvsim('square_grid_100mjy_config.yaml')

Mean of empty slice.
invalid value encountered in double_scalars
No spectral_type specified for GLEAM, using 'flat'.


Nbls: 61
Ntimes: 1
Nfreqs: 1
Nsrcs: 191878
Tasks:  61.0
1.64% completed. 0:00:00.211479  elapsed. 0:00:12.688723 remaining. 

3.28% completed. 0:00:00.225081  elapsed. 0:00:06.639881 remaining. 

4.92% completed. 0:00:00.237677  elapsed. 0:00:04.595081 remaining. 

6.56% completed. 0:00:00.251624  elapsed. 0:00:03.585640 remaining. 

8.20% completed. 0:00:00.263696  elapsed. 0:00:02.953392 remaining. 

9.84% completed. 0:00:00.278387  elapsed. 0:00:02.551879 remaining. 

11.48% completed. 0:00:00.290736  elapsed. 0:00:02.242818 remaining. 

13.11% completed. 0:00:00.301991  elapsed. 0:00:02.000689 remaining. 

14.75% completed. 0:00:00.314917  elapsed. 0:00:01.819520 remaining. 

16.39% completed. 0:00:00.326396  elapsed. 0:00:01.664618 remaining. 

18.03% completed. 0:00:00.339220  elapsed. 0:00:01.541908 remaining. 

19.67% completed. 0:00:00.350801  elapsed. 0:00:01.432436 remaining. 

21.31% completed. 0:00:00.363190  elapsed. 0:00:01.341008 remaining. 

22.95% completed. 0:00:00.3